# Generated by Django 3.2 on 2021-05-01 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_cart_final_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, verbose_name='Финальная цена'),
        ),
    ]
